development:
  adapter: mysql2
  database: universitapp
  username: root
  password: toor
  host: localhost

test: &test
  adapter: mysql2
  database: universitapp
  username: root
  password: toor
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  pool: 5
  database: universitapp
  username: root  
  password:        
  host: localhost                

selenium:
  <<: *test

cucumber:
  <<: *test